### ISSUE TITLE
How to get source and target .hdr files ? 

### ISSUE THREAD

**Issue by kelisiya** [ken2576/nelf#1]
Firstly, congrats to the team for the interesting results.  I want to  test your model in real world , I have some image and mask ,but how to get .hdr files ?

**Comment by ken2576** [comment]
Hi,

Thanks for checking out our repo.
You can find some environment maps here.
http://indoor.hdrdb.com/
http://outdoor.hdrdb.com/
For more data, it should be freely available by searching hdr map free or similar keywords.

**Comment by kelisiya** [comment]
> Hi,
> 
> Thanks for checking out our repo. You can find some environment maps here. http://indoor.hdrdb.com/ http://outdoor.hdrdb.com/ For more data, it should be freely available by searching hdr map free or similar keywords.

Thanks for your reply! I have a new question. I found out that the demo finally relights the single image. How do I implement this part in your code?

**Comment by ken2576** [comment]
Our method takes 5 input views for now.
It might be possible to just repeat one view for 5 times for a quick hack.
Though I don't think single-view input would work well.
We show that the method degrades heavily using 2 input views.

**Comment by prraoo** [comment]
Hello @ken2576 ,

Thank you for sharing your amazing work. 

I observed that the hdr files used in the work are downscaled versions of very high-resolution environment maps. Unfortunately, I am facing difficulties in downscaling the environment maps. Could you let me know how do you pre-process the hdr files?
