### ISSUE TITLE
Multiplayer、 complex environment

### ISSUE THREAD

**Issue by zhanghongyong123456** [ken2576/nelf#2]
Can scenes and multiple people realize light and shadow retake

**Comment by ken2576** [comment]
I am not quite sure what you meant.
However, this work is focusing on single person portrait for now.

**Comment by zhanghongyong123456** [comment]
> I am not quite sure what you meant. However, this work is focusing on single person portrait for now.
 what imean is like this paper  realize
![image](https://user-images.githubusercontent.com/48466610/142963056-8adae67f-118a-4fb5-a494-cc1d0e0a7145.png)
https://github.com/augmentedperception/total_relighting

**Comment by zhanghongyong123456** [comment]
> I am not quite sure what you meant. However, this work is focusing on single person portrait for now.


Do you have any good project recommendations in this regard? Regarding re-lighting，like total_relighting

**Comment by ken2576** [comment]
Our work focuses on view synthesis and relighting simultaneously, and the paper you posted is more like single-image relighting. I think it is also an extension to Tiancheng's SIPR paper (https://cseweb.ucsd.edu/~ravir/portrait_relighting.pdf).
For recommendations, you could look into relighting for dynamic video (https://arxiv.org/pdf/2104.00484.pdf) or using more accessible devices to do light transport acquisition (https://grail.cs.washington.edu/projects/Light_Stage_on_Every_Desk/).

**Comment by zhanghongyong123456** [comment]
> Our work focuses on view synthesis and relighting simultaneously, and the paper you posted is more like single-image relighting. I think it is also an extension to Tiancheng's SIPR paper (https://cseweb.ucsd.edu/~ravir/portrait_relighting.pdf). For recommendations, you could look into relighting for dynamic video (https://arxiv.org/pdf/2104.00484.pdf) or using more accessible devices to do light transport acquisition (https://grail.cs.washington.edu/projects/Light_Stage_on_Every_Desk/).

Thank you very much for your reply
