### ISSUE TITLE
Missing file dataset_color.npy

### ISSUE THREAD

**Issue by Sibylle-Van-Hove** [ken2576/nelf#4]
Getting file-not-found error for the file `./data/dataset_color.npy` when running `run_test.py`. Does this file need to be downloaded from somewhere?

**Comment by ken2576** [comment]
Please check out the link
https://drive.google.com/file/d/1W93cU97EFLmzAvbKLB3LUvo61RWx59kY/view
You can find the steps here
https://github.com/ken2576/nelf#training
